name: Python Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Adjust the Python version as needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: 🔍 Code mit pylint prüfen
      run: |
          pylint $(git ls-files '*.py')  # Linting für alle Python-Dateien

    - name: Run Tests
      run: |
        python -m unittest tests.test_questions
      uses: actions/checkout@v4